// Generated by ts-to-zod
import { z } from "zod";
import { WebUntisDay, WebUntisElementType } from "./types";

export const schoolYearSchema = z.object({
  name: z.string(),
  id: z.number(),
  startDate: z.date(),
  endDate: z.date(),
});

export const messagesOfDaySchema = z.object({
  id: z.number(),
  subject: z.string(),
  text: z.string(),
  isExpanded: z.boolean(),
  attachments: z.array(z.any()),
});

export const newsWidgetSchema = z.object({
  systemMessage: z.any().optional(),
  messagesOfDay: z.array(messagesOfDaySchema),
  rssUrl: z.string(),
});

export const inboxSenderSchema = z.object({
  className: z.null(),
  displayName: z.string(),
  imageUrl: z.string().nullable(),
  userId: z.number(),
});

export const shortDataSchema = z.object({
  id: z.number(),
  name: z.string(),
  longname: z.string(),
  orgname: z.string().optional(),
  orgid: z.number().optional(),
});

export const lessonSchema = z.object({
  id: z.number(),
  date: z.number(),
  startTime: z.number(),
  endTime: z.number(),
  kl: z.array(shortDataSchema),
  te: z.array(shortDataSchema),
  su: z.array(shortDataSchema),
  ro: z.array(shortDataSchema),
  lstext: z.string().optional(),
  lsnumber: z.number(),
  activityType: z.union([z.literal("Unterricht"), z.string()]).optional(),
  lessonType: z.union([z.literal("Unterricht"), z.string()]).optional(),
  code: z.union([z.literal("cancelled"), z.literal("irregular")]).optional(),
  info: z.string().optional(),
  substText: z.string().optional(),
  statflags: z.string().optional(),
  sg: z.string().optional(),
  bkRemark: z.string().optional(),
  bkText: z.string().optional(),
  subject: z.string().optional(),
});

export const homeworkSchema = z.object({
  attachments: z.array(z.any()),
  completed: z.boolean(),
  date: z.number(),
  dueDate: z.number(),
  id: z.number(),
  lessonId: z.number(),
  remark: z.string(),
  text: z.string(),
});

export const homeworkRecordSchema = z.object({
  elementIds: z.array(z.number()),
  homeworkId: z.number(),
  teacherId: z.number(),
});

export const teacherSchema = z.object({
  id: z.number(),
  name: z.string(),
  foreName: z.string(),
  longName: z.string(),
  foreColor: z.string().optional(),
  backColor: z.string().optional(),
  active: z.boolean().optional(),
  dids: z.array(z.any()).optional(),
  title: z.string().optional(),
});

export const subjectSchema = z.object({
  active: z.boolean(),
  alternateName: z.string(),
  id: z.number(),
  longName: z.string(),
  name: z.string(),
  backColor: z.string().optional(),
  foreColor: z.string().optional(),
});

export const webUntisDaySchema = z.enum(WebUntisDay);

export const timeUnitSchema = z.object({
  name: z.string(),
  startTime: z.number(),
  endTime: z.number(),
});

export const timegridSchema = z.object({
  day: webUntisDaySchema,
  timeUnits: z.array(timeUnitSchema),
});

export const examSchema = z.object({
  id: z.number(),
  examType: z.string(),
  name: z.string(),
  studentClass: z.array(z.string()),
  assignedStudents: z.array(
    z.object({
      klasse: z.object({
        id: z.number(),
        name: z.string(),
      }),
      displayName: z.string(),
      id: z.number(),
    }),
  ),
  examDate: z.number(),
  startTime: z.number(),
  endTime: z.number(),
  subject: z.string(),
  teachers: z.array(z.string()),
  rooms: z.array(z.string()),
  text: z.string(),
  grade: z.string().optional(),
});

export const webUntisElementTypeSchema = z.enum(WebUntisElementType);

export const webElementSchema = z.object({
  type: webUntisElementTypeSchema,
  id: z.number(),
  orgId: z.number(),
  missing: z.boolean(),
  state: z.union([z.literal("REGULAR"), z.literal("ABSENT"), z.literal("SUBSTITUTED")]),
});

export const webElementDataSchema = webElementSchema.extend({
  element: z.object({
    type: z.number(),
    id: z.number(),
    name: z.string(),
    longName: z.string().optional(),
    displayname: z.string().optional(),
    alternatename: z.string().optional(),
    canViewTimetable: z.boolean(),
    externalKey: z.string().optional(),
    roomCapacity: z.number(),
  }),
});

export const webTimetableIsSchema = z.union([
  z.object({
    event: z.boolean(),
    standard: z.boolean(),
  }),
  z.object({
    event: z.boolean(),
    substitution: z.boolean(),
  }),
  z.object({
    event: z.boolean(),
    cancelled: z.boolean(),
  }),
  z.object({
    event: z.boolean(),
    exam: z.boolean(),
  }),
  z.object({
    event: z.boolean(),
    roomSubstitution: z.boolean(),
  }),
  z.object({
    event: z.boolean(),
    additional: z.boolean(),
  }),
]);

export const webTimetableExamSchema = z.object({
  date: z.number(),
  id: z.number(),
  markSchemaId: z.number(),
  name: z.string(),
});

export const webTimetableElementRefSchema = z.object({
  id: z.number(),
  missing: z.boolean(),
  orgId: z.number(),
  state: z.string(),
  type: z.number(),
});

export const webElementInfoSchema = z.object({
  alternatename: z.string(),
  canViewTimetable: z.boolean(),
  displayname: z.string(),
  id: z.number(),
  longName: z.string(),
  name: z.string(),
  roomCapacity: z.number(),
  type: z.number(),
});

export const webTeacherInfoSchema = z.object({
  canViewTimetable: z.boolean(),
  externKey: z.string(),
  id: z.number(),
  name: z.string(),
  roomCapacity: z.number(),
  type: z.number(),
});

export const webTimetableResolvedElementSchema = webTimetableElementRefSchema.extend({
  element: webElementInfoSchema,
});

export const webTimetableResolvedTeacherElementSchema = webTimetableElementRefSchema.extend({
  element: webTeacherInfoSchema,
});

export const studentSchema = z.object({
  id: z.number(),
  key: z.string(),
  name: z.string(),
  foreName: z.string(),
  longName: z.string(),
  gender: z.string(),
});

export const roomSchema = z.object({
  active: z.boolean(),
  building: z.string(),
  id: z.number(),
  longName: z.string(),
  name: z.string(),
  backColor: z.string().optional(),
  foreColor: z.string().optional(),
});

export const klasseSchema = z.object({
  active: z.boolean(),
  id: z.number(),
  longName: z.string(),
  name: z.string(),
  teacher1: z.number().optional(),
  teacher2: z.number().optional(),
});

export const departmentSchema = z.object({
  id: z.number(),
  name: z.string(),
  longName: z.string(),
});

export const holidaySchema = z.object({
  name: z.string(),
  longName: z.string(),
  id: z.number(),
  startDate: z.number(),
  endDate: z.number(),
});

export const colorEntitySchema = z.object({
  foreColor: z.string(),
  backColor: z.string(),
});

export const lsEntitySchema = z.object({
  ls: colorEntitySchema.optional().nullable(),
  oh: colorEntitySchema.optional().nullable(),
  sb: colorEntitySchema.optional().nullable(),
  bs: colorEntitySchema.optional().nullable(),
  ex: colorEntitySchema.optional().nullable(),
});

export const codesEntitySchema = z.object({
  cancelled: colorEntitySchema.optional().nullable(),
  irregular: colorEntitySchema.optional().nullable(),
});

export const statusDataSchema = z.object({
  lstypes: z.array(lsEntitySchema),
  codes: z.array(codesEntitySchema),
});

export const excuseSchema = z.object({
  id: z.number(),
  text: z.string(),
  excuseDate: z.number(),
  excuseStatus: z.string(),
  isExcused: z.boolean(),
  userId: z.number(),
  username: z.string(),
});

export const inboxMessageSchema = z.object({
  allowMessageDeletion: z.boolean(),
  contentPreview: z.string().nullable(),
  hasAttachments: z.boolean(),
  id: z.number(),
  isMessageRead: z.boolean(),
  isReply: z.boolean(),
  isReplyAllowed: z.boolean(),
  sender: inboxSenderSchema,
  sentDateTime: z.string(),
  subject: z.string(),
});

export const homeworksSchema = z.object({
  homeworks: z.array(homeworkSchema),
  lessons: z.array(lessonSchema.partial()),
  records: z.array(homeworkRecordSchema),
  teachers: z.array(teacherSchema.partial()),
});

export const webTimetableRowSchema = z.object({
  cellState: z.string(),
  code: z.number(),
  date: z.number(),
  endTime: z.number(),
  hasInfo: z.boolean(),
  hasPeriodText: z.boolean(),
  id: z.number(),
  is: webTimetableIsSchema,
  lessonCode: z.string(),
  lessonId: z.number(),
  lessonNumber: z.number(),
  lessonText: z.string(),
  periodAttachments: z.array(z.unknown()),
  periodInfo: z.string(),
  periodText: z.string(),
  priority: z.number(),
  roomCapacity: z.number(),
  startTime: z.number(),
  studentCount: z.number(),
  substText: z.string(),
  studentGroup: z.string().optional(),
  exam: webTimetableExamSchema.optional(),
  elements: z.array(webTimetableElementRefSchema),
  classes: z.array(webTimetableResolvedElementSchema),
  rooms: z.array(webTimetableResolvedElementSchema),
  subjects: z.array(webTimetableResolvedElementSchema),
  teachers: z.array(webTimetableResolvedTeacherElementSchema),
  students: z.array(z.unknown()),
});

export const absenceSchema = z.object({
  id: z.number(),
  startDate: z.number(),
  endDate: z.number(),
  startTime: z.number(),
  endTime: z.number(),
  createDate: z.number(),
  lastUpdate: z.number(),
  createdUser: z.string(),
  updatedUser: z.string(),
  reasonId: z.number(),
  reason: z.string(),
  text: z.string(),
  interruptions: z.tuple([]),
  canEdit: z.boolean(),
  studentName: z.string(),
  excuseStatus: z.string(),
  isExcused: z.boolean(),
  excuse: excuseSchema,
});

export const inboxSchema = z.object({
  incomingMessages: z.array(inboxMessageSchema),
  readConfirmationMessages: z.array(inboxMessageSchema),
});

export const webApiTimetableSchema = z.array(webTimetableRowSchema);

export const absencesSchema = z.object({
  absences: z.array(absenceSchema).optional(),
  absenceReasons: z
    .array(
      z.object({
        id: z.number(),
        name: z.string(),
      }),
    )
    .optional(),
  excuseStatuses: z.boolean().optional().nullable(),
  showAbsenceReasonChange: z.boolean().optional(),
  showCreateAbsence: z.boolean().optional(),
});
