// Generated by ts-to-zod
import { z } from 'zod';
import { WebUntisDay, WebUntisElementType } from './types';

export const schoolYearSchema = z.object({
    name: z.string(),
    id: z.number(),
    startDate: z.date(),
    endDate: z.date(),
});

export const messagesOfDaySchema = z.object({
    id: z.number(),
    subject: z.string(),
    text: z.string(),
    isExpanded: z.boolean(),
    attachments: z.array(z.any()),
});

export const newsWidgetSchema = z.object({
    systemMessage: z.any().optional(),
    messagesOfDay: z.array(messagesOfDaySchema),
    rssUrl: z.string(),
});

export const inboxSenderSchema = z.object({
    className: z.null(),
    displayName: z.string(),
    imageUrl: z.string().nullable(),
    userId: z.number(),
});

export const shortDataSchema = z.object({
    id: z.number(),
    name: z.string(),
    longname: z.string(),
    orgname: z.string().optional(),
    orgid: z.number().optional(),
});

export const lessonSchema = z.object({
    id: z.number(),
    date: z.number(),
    startTime: z.number(),
    endTime: z.number(),
    kl: z.array(shortDataSchema),
    te: z.array(shortDataSchema),
    su: z.array(shortDataSchema),
    ro: z.array(shortDataSchema),
    lstext: z.string().optional(),
    lsnumber: z.number(),
    activityType: z.union([z.literal('Unterricht'), z.string()]).optional(),
    code: z.union([z.literal('cancelled'), z.literal('irregular')]).optional(),
    info: z.string().optional(),
    substText: z.string().optional(),
    statflags: z.string().optional(),
    sg: z.string().optional(),
    bkRemark: z.string().optional(),
    bkText: z.string().optional(),
});

export const homeworkSchema = z.object({
    attachments: z.array(z.any()),
    completed: z.boolean(),
    date: z.number(),
    dueDate: z.number(),
    id: z.number(),
    lessonId: z.number(),
    remark: z.string(),
    text: z.string(),
});

export const subjectSchema = z.object({
    active: z.boolean(),
    alternateName: z.string(),
    id: z.number(),
    longName: z.string(),
    name: z.string(),
    backColor: z.string().optional(),
    foreColor: z.string().optional(),
});

export const webUntisDaySchema = z.enum(WebUntisDay);

export const timeUnitSchema = z.object({
    name: z.string(),
    startTime: z.number(),
    endTime: z.number(),
});

export const timegridSchema = z.object({
    day: webUntisDaySchema,
    timeUnits: z.array(timeUnitSchema),
});

export const examSchema = z.object({
    id: z.number(),
    examType: z.string(),
    name: z.string(),
    studentClass: z.array(z.string()),
    assignedStudents: z.array(
        z.object({
            klasse: z.object({
                id: z.number(),
                name: z.string(),
            }),
            displayName: z.string(),
            id: z.number(),
        }),
    ),
    examDate: z.number(),
    startTime: z.number(),
    endTime: z.number(),
    subject: z.string(),
    teachers: z.array(z.string()),
    rooms: z.array(z.string()),
    text: z.string(),
    grade: z.string().optional(),
});

export const webUntisElementTypeSchema = z.enum(WebUntisElementType);

export const webElementSchema = z.object({
    type: webUntisElementTypeSchema,
    id: z.number(),
    orgId: z.number(),
    missing: z.boolean(),
    state: z.union([z.literal('REGULAR'), z.literal('ABSENT'), z.literal('SUBSTITUTED')]),
});

export const webElementDataSchema = webElementSchema.extend({
    element: z.object({
        type: z.number(),
        id: z.number(),
        name: z.string(),
        longName: z.string().optional(),
        displayname: z.string().optional(),
        alternatename: z.string().optional(),
        canViewTimetable: z.boolean(),
        externalKey: z.string().optional(),
        roomCapacity: z.number(),
    }),
});

export const webApiTimetableSchema = z.object({
    id: z.number(),
    lessonId: z.number(),
    lessonNumber: z.number(),
    lessonCode: z.string(),
    lessonText: z.string(),
    periodText: z.string(),
    hasPeriodText: z.literal(false),
    periodInfo: z.string(),
    periodAttachments: z.tuple([]),
    substText: z.string(),
    date: z.number(),
    startTime: z.number(),
    endTime: z.number(),
    elements: z.array(webElementSchema),
    studentGroup: z.string(),
    hasInfo: z.boolean(),
    code: z.number(),
    cellState: z.union([z.literal('STANDARD'), z.literal('SUBSTITUTION'), z.literal('ROOMSUBSTITUTION')]),
    priority: z.number(),
    is: z.object({
        roomSubstitution: z.boolean().optional(),
        substitution: z.boolean().optional(),
        standard: z.boolean().optional(),
        event: z.boolean(),
    }),
    roomCapacity: z.number(),
    studentCount: z.number(),
    classes: z.array(webElementDataSchema),
    teachers: z.array(webElementDataSchema),
    subjects: z.array(webElementDataSchema),
    rooms: z.array(webElementDataSchema),
    students: z.array(webElementDataSchema),
});

export const teacherSchema = z.object({
    id: z.number(),
    name: z.string(),
    foreName: z.string(),
    longName: z.string(),
    foreColor: z.string(),
    backColor: z.string(),
});

export const studentSchema = z.object({
    id: z.number(),
    key: z.number(),
    name: z.string(),
    foreName: z.string(),
    longName: z.string(),
    gender: z.string(),
});

export const roomSchema = z.object({
    id: z.number(),
    name: z.string(),
    longName: z.string(),
    alternateName: z.union([z.string(), z.literal('')]),
    active: z.boolean(),
    foreColor: z.string(),
    backColor: z.string(),
});

export const klasseSchema = z.object({
    active: z.boolean(),
    id: z.number(),
    longName: z.string(),
    name: z.string(),
    teacher1: z.number().optional(),
    teacher2: z.number().optional(),
});

export const departmentSchema = z.object({
    id: z.number(),
    name: z.string(),
    longName: z.string(),
});

export const holidaySchema = z.object({
    name: z.string(),
    longName: z.string(),
    id: z.number(),
    startDate: z.number(),
    endDate: z.number(),
});

export const colorEntitySchema = z.object({
    foreColor: z.string(),
    backColor: z.string(),
});

export const lsEntitySchema = z.object({
    ls: colorEntitySchema.optional().nullable(),
    oh: colorEntitySchema.optional().nullable(),
    sb: colorEntitySchema.optional().nullable(),
    bs: colorEntitySchema.optional().nullable(),
    ex: colorEntitySchema.optional().nullable(),
});

export const codesEntitySchema = z.object({
    cancelled: colorEntitySchema.optional().nullable(),
    irregular: colorEntitySchema.optional().nullable(),
});

export const statusDataSchema = z.object({
    lstypes: z.array(lsEntitySchema),
    codes: z.array(codesEntitySchema),
});

export const excuseSchema = z.object({
    id: z.number(),
    text: z.string(),
    excuseDate: z.number(),
    excuseStatus: z.string(),
    isExcused: z.boolean(),
    userId: z.number(),
    username: z.string(),
});

export const inboxMessageSchema = z.object({
    allowMessageDeletion: z.boolean(),
    contentPreview: z.string().nullable(),
    hasAttachments: z.boolean(),
    id: z.number(),
    isMessageRead: z.boolean(),
    isReply: z.boolean(),
    isReplyAllowed: z.boolean(),
    sender: inboxSenderSchema,
    sentDateTime: z.string(),
    subject: z.string(),
});

export const absenceSchema = z.object({
    id: z.number(),
    startDate: z.number(),
    endDate: z.number(),
    startTime: z.number(),
    endTime: z.number(),
    createDate: z.number(),
    lastUpdate: z.number(),
    createdUser: z.string(),
    updatedUser: z.string(),
    reasonId: z.number(),
    reason: z.string(),
    text: z.string(),
    interruptions: z.tuple([]),
    canEdit: z.boolean(),
    studentName: z.string(),
    excuseStatus: z.string(),
    isExcused: z.boolean(),
    excuse: excuseSchema,
});

export const inboxSchema = z.object({
    incomingMessages: z.array(inboxMessageSchema),
    readConfirmationMessages: z.array(inboxMessageSchema),
});

export const absencesSchema = z.object({
    absences: z.array(absenceSchema),
    absenceReasons: z.tuple([]),
    excuseStatuses: z.boolean(),
    showAbsenceReasonChange: z.boolean(),
    showCreateAbsence: z.boolean(),
});
